server:
port: 8080

spring:
  redis:
    host: 192.168.233.128
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        max-wait: 6000ms
        min-idle: 4
